### ISSUE TITLE
error opening project with many issues

### ISSUE THREAD

**Issue by gaglage** [tosher/Redlime#1]
I got this error trying to open a project with a big amount of issues

Text 3\Packages\Redlime\redlime.py", line 335, in run
selected_header = max([h for h in headers if h.b < selected.b])
ValueError: max() arg is an empty sequence

**Comment by tosher** [comment]
Which command you trying to run?
Maybe you run **Redlime issue: Magic enter** not from issue screen?

To get issues list you can run commands:
- Redlime: Project issues (get projects list and then issues)
- Redlime: List queries (as is in SubRed)

**Comment by gaglage** [comment]
I try to get issues using _Redlime: Project issues_ option. After I select this option I try to select one of my projects in redmine. If I choose a project not many issues the plugin works fine, in other case crushes

**Comment by tosher** [comment]
How many issues you have in big project? With ~1000 issues on my test env. plugin works ok, waiting, slow, but shows issues.

**Comment by tosher** [comment]
I'll add **paging** into issues list in next version.

**Comment by tosher** [comment]
Please, try the new version (1.1.0)

**Comment by gaglage** [comment]
I tried with the updated version and It works now. Thanks!

**Comment by tosher** [comment]
Ok, thanks!
