### ISSUE TITLE
Can't edit keymap

### ISSUE THREAD

**Issue by softloft38p-michael** [tosher/Redlime#14]
When I try to edit the keymap for redlime the console returns: `error: The settings file "res://Packages/Redlime/Default.sublime-keymap" could not be opened`. Ideal behavior is that the keybinding menu should open the "res://Packages/Redlime/Default (Platform).sublime-keymap" and the user's "res://Packages/User/Default.sublime-keymap" side by side for editing.

**Comment by tosher** [comment]
Thank you! I will fix it soon,

**Comment by tosher** [comment]
Fixed:
https://github.com/tosher/Redlime/releases/tag/v1.6.4
