### ISSUE TITLE
Assign filter hangs

### ISSUE THREAD

**Issue by mgraham-cracker** [tosher/Redlime#2]
I have configured my user setttings to link to a Redmine instance. When I perform a "List Queries" request I am returned a set of ticket items. But when I attempt to issue an "Assign Filter" operation it causes Sublime Text to hang. In the end I have to kill the process and re-open Sublime Text.

I am using the most recent version of Sublime Text 3
![screenclip](https://cloud.githubusercontent.com/assets/16342755/23674881/6b27631a-0345-11e7-80c5-3f21025e22cc.png)

**Comment by tosher** [comment]
The same with issues list by project (not queries), then by assign filter - hangs too?

**Comment by mgraham-cracker** [comment]
Yes, if I list out issues by project, then try to apply a filter it hangs as well.

**Comment by tosher** [comment]
How many issues in the project?

**Comment by mgraham-cracker** [comment]
There are 53 issues in one project, but those are just active. There are thousands of closed ones.
On Mar 13, 2017 12:48 PM, tosher <notifications@github.com> wrote:How many issues in the project?

**Comment by tosher** [comment]
Thanks for the info, i'll check it.

**Comment by tosher** [comment]
Small update, please check the problem with this new version:
https://github.com/tosher/Redlime/releases/tag/1.4.0

**Comment by mgraham-cracker** [comment]
That appeared to resolve the issue. Thanks!
