### ISSUE TITLE
Custom fields are not displaying

### ISSUE THREAD

**Issue by mgraham-cracker** [tosher/Redlime#3]
Custom fields don't display. This is a copy of my settings file. Branch and Department are custom fields for me in Redmine, Any custom field I attempt to add fails to appear, neither a label or null value. I have highlighted the custom field definitions in the configuration below:

{
    "redmine_url" : "xxxxxxxxxx",
    "api_key": "xxxxxxxxxx",
    "projects_filter": ["da", "cm", "da-incomming", "workflow-incoming"],
    "query_page_size": 40,
    "syntax_file": "Packages/Redlime/Redlime.tmLanguage",
    "issue_list_columns": [
        { "prop": "id", "colname": "#", "custom": false, "align": "right" },
        { "prop": "fixed_version", "colname": "Version", "custom": false},
        { "prop": "tracker", "colname": "Type", "custom": false},
        { "prop": "priority", "colname": "Prior.", "custom": false},
        { "prop": "status", "colname": "Status", "custom": false},
        { "prop": "subject", "colname": "Subject", "custom": false, "maxlen": 80},
        { "prop": "assigned_to", "colname": "Assigned", "custom": false},
    ],
    "issue_view_columns": [
        { "prop": "id", "colname": "Issue", "custom": false},
        { "prop": "project", "colname": "Project", "custom": false},
        { "prop": "status", "colname": "Status", "custom": false},
        { "prop": "priority", "colname": "Priority", "custom": false},
        { "prop": "assigned_to", "colname": "Assigned to", "custom": false},
        { "prop": "category", "colname": "Category", "custom": false},
        { "prop": "fixed_version", "colname": "Target Version", "custom": false},
        **{ "prop": "department", "colname": "Department", "custom": true},
        { "prop": "branch", "colname": "Branch", "custom": true},**
        { "prop": "time_to_reaction", "colname": "Time to reaction", "custom": false},
        { "prop": "waiting_response", "colname": "Waiting response", "custom": false},
        { "prop": "start_date", "colname": "Start date", "custom": false, "type": "datetime"},
        { "prop": "due_date", "colname": "Due date", "custom": false, "type": "datetime"},
        { "prop": "estimated_hours", "colname": "Estimated Time", "custom": false},
        { "prop": "author", "colname": "Author", "custom": false},
        { "prop": "created_on", "colname": "Creation date", "custom": false, "type": "datetime"}
    ]
}

![screenclip 1](https://cloud.githubusercontent.com/assets/16342755/23677622/e672459a-034e-11e7-8622-8c7357936e73.png)

**Comment by tosher** [comment]
I'll try to check this moment.

**Comment by tosher** [comment]
This custom fields in redmine has names "department" and "branch", not "Department", "Branch", for example? (fields are case sensitive)

**Comment by mgraham-cracker** [comment]
You are correct, that was my mistake. After updating the fields to capitalized Department and Branch they worked.

Sorry about that, I was sure I tried both ways.

Thanks for the help

**Comment by tosher** [comment]
Fine. Thanks for your interest in the plugin :)
