### ISSUE TITLE
Use buffer for comments and editing issue descriptions

### ISSUE THREAD

**Issue by kostajh** [tosher/Redlime#7]
I'm wondering what you think of using buffers for editing comments and issue descriptions, much like [GitSavvy](https://github.com/divmain/GitSavvy) does for writing commit messages. 

Using a full buffer would make writing lengthier comments or description edits much easier -- currently I keep submitting comments/issue edits before they are ready because "Enter" automatically submits the text. If we use a buffer we'd also get the advantages of syntax highlighting and any other plugins that operate on the buffer.

**Comment by tosher** [comment]
Yes, it's exists in plans. Now, I make the same plugin for [gitlab](https://github.com/tosher/StGitlab) and it will be there, after that i'll move some features to this plugin.

**Comment by tosher** [comment]
Please, check the new version:
https://github.com/tosher/Redlime/releases/tag/1.5.0
