### ISSUE TITLE
Request for extras

### ISSUE THREAD

**Issue by 27escape** [tosher/Redlime#8]
Many thanks for this work, I am finding it very useful. I wonder if you have considered adding the ability to create a new issue or to log time against an issue or a project - that would make it pretty perfect for me!

No worries if you are too busy with other stuff or that you do not have this need

kevin

**Comment by tosher** [comment]
* `create a new issue` - already done and will be in next version;
* `log time against an issue or a project` - would you describe it in more detail?

**Comment by tosher** [comment]
https://github.com/tosher/Redlime/releases/tag/1.6.0

**Comment by 27escape** [comment]
Many thanks for the work on creating a new issue!

Regarding the logging of time, it is possible to log time against an issue or a project. There is a general purpose webpage at your redmine instance at /time_entries/new or, when using the REST API you can  POST data to  /time_entries.xml as seen in https://www.redmine.org/projects/redmine/wiki/Rest_TimeEntries

I guess its not something you need to do. 

regards
kevin

**Comment by tosher** [comment]
* Time entries: ■■■■■■■■□□ 80% (create project/issue time entry, issue entries showing)

**Comment by tosher** [comment]
https://github.com/tosher/Redlime/releases/tag/1.6.1
