### ISSUE TITLE
Submitting an updated description

### ISSUE THREAD

**Issue by kostajh** [tosher/Redlime#9]
I'm using the `six` plugin so I have Vim keybindings. I use insert mode to be able to use the keyboard shortcuts. After I've updated a description, I can't figure out what I'm supposed to press to submit the new description. Sorry if I'm missing something obvious!

**Comment by tosher** [comment]
Default shortcut is <kbd>Ctrl</kbd>+<kbd>s</kbd> (<kbd>Cmd</kbd>+<kbd>s</kbd> on Mac), like native save. Or you can call a command `Redlime: Save edit` from Command Palette.

**Comment by firstdayofjune** [comment]
It also works with <kbd>Ctrl</kbd> + <kbd>S</kbd> on Mac, hitting <kbd>Cmd</kbd> + <kbd>S</kbd> opens the native save dialogue (which would result in the issue being saved on disk, but not in an update on redmine).

**Comment by tosher** [comment]
Yes, you're right, I didn't the special MacOS shortcuts :( But, a shortcut key can be changed manually. In next version, I'll fix it.

**Comment by tosher** [comment]
Please, check the new version:
https://github.com/tosher/Redlime/releases/tag/v1.6.2

**Comment by firstdayofjune** [comment]
It now works as expected, thanks for the update!
